version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
    - go generate ./internal/static/
builds:
  -
    id: omnivue-darwin
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/stevencrawford/omnivue/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  -
    id: omnivue-windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/stevencrawford/omnivue/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
  -
    id: omnivue-linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/stevencrawford/omnivue/version.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  -
    id: omnivue-archive
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        formats:
          - zip
    files:
      - LICENSE
      - CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: omnivue-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    ids:
      - omnivue-linux
    homepage: https://github.com/stevencrawford/omnivue
    maintainer: Steven Crawford
    description: "Omnivue is an AI/LLM session manager for coding agents"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
release:
  use_existing_draft: true
