// Barrel file — re-exports types and API functions for backward compatibility.
// Prefer importing directly from ./types.ts and ./apiClient.ts in new code.

export type {
  Session,
  Source,
  StepEvent,
  StepTokens,
  Message,
  ToolCall,
  ScratchFile,
  StatusInfo,
  Plan,
  DiffFile,
  FileEdit,
  SearchResult,
  Folder,
  Bookmark,
} from "./types";

export {
  fetchSessions,
  fetchSession,
  fetchMessages,
  fetchPlan,
  fetchDiffs,
  fetchEdits,
  setSessionName,
  clearSessionName,
  fetchResumeCommand,
  fetchSources,
  addSource,
  removeSource,
  updateSource,
  resetApp,
  fetchConfig,
  setConfig,
  fetchRecentSearches,
  addRecentSearches,
  fetchStatus,
  fetchSearch,
  fetchFolders,
  createFolder,
  updateFolder,
  deleteFolder,
  fetchFolderSessions,
  assignSessionToFolder,
  unassignSessionFromFolder,
  fetchScratchFiles,
  createScratchFile,
  getScratchFile,
  updateScratchFile,
  renameScratchFile,
  deleteScratchFile,
  fetchAllScratchFiles,
  fetchBookmarks,
  createBookmark,
  deleteBookmark,
} from "./apiClient";
